#!/usr/bin/expect 
# Write to multiple users from a prepared file  
# or a message input interactively  
  
if ($argc<3) {  
send_user "usage: $argv0 project branch action  ... "  
exit  
}
set timeout 10
set project  [lindex $argv 0]
set action [lindex $argv 1]
set branch [lindex $argv 2]

spawn sh ./deploy_project.sh

expect "*the project:" 
send "$project\n"

expect "*the action:" 
send "$action\n"

expect "*the branch:" 
send "$branch\n"

interact

